### ISSUE TITLE
Hero suddenly switch lanes.

### ISSUE THREAD

**Issue by Oliver-1xok** [julienlegault/Artifact-Javascript#1]
Third Lane was active. I put the improvement Assured Destruction on the first lane. A red hero (Centaur Warrunner) suddenly switched from third to first lane. 

![CW_Switch](https://user-images.githubusercontent.com/40916755/57582236-7d873080-74c2-11e9-9838-f8541d107857.jpg)

**Comment by julienlegault** [comment]
If you look in the upper right corner, the bot played intimidation. Without animations it can be difficult sometimes to tell what is happening, doubly so because bots play nearly instantly. Everything in this screenshot is working as intended.
